apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-app
  namespace: default
  labels:
    app: hw-app
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
      - name: hw-app
        image: host.minikube.internal:5000/hw-app:20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
      restartPolicy: Always