apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-app
  namespace: hw-app
  labels:
    app: hw-app
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
      - name: hw-app
        image: 192.168.49.2:5000/hw-app:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always